#!/usr/bin/env bash
#Bash script installs Nginx server and redirects /redirect_me to
# another page
# The redirection must be a “301 Moved Permanently”
apt-get -y update
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://youtu.be/iJ5x5gHg3P0?si=tq_P7iVWltiCz6pa permanent;" /etc/nginx/sites-available/default
service nginx restart
