#!/usr/bin/env bash
# This script doubles the numof webservers and adds new configs

# installation of nginx
apt-get  update ; apt-get -y install nginx

the_string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$the_string/" /etc/nginx/nginx.conf

# nginx restarting
sudo service nginx restart
