#!/bin/bash/env bash
# Check if the script is called with an argument

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Get the IP address from the argument
ip_address="$1"

# Ping the IP address 5 times and display the results
ping_result=$(ping -c 5 "$ip_address")

# Print the ping results
echo "$ping_result"
