#!/usr/bin/env bash
# Fixes Ngnix server to listenn on port 80
string="listen 80 default_server;"
old_string="listen 8080 default_server;"
sudo sed -i "s/$old_string/$string/" /etc/nginx/sites-enabled/default
sudo sed -i '22d' /etc/nginx/sites-enabled/default
sudo service nginx start
