#!/usr/bin/env bash
#  Bash script that displays Best School 10 times
# For the 9th iteration, displays Best School and then Hi on a new line.
# Using While loop and if statement

counter=1
while [ $((counter++)) -lt 10 ];
do
    echo "Best School"
    if [ $counter -eq '9' ];
    then
        echo "Hi"
    fi
done
