#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# except for the 4th("bad luck") and 8th("good luck") iterations
# Using the while loop, if, elif, else statements

counter=1
while [ $((counter++)) -lt 10 ]
do
    if [[ $counter -eq 4 ]]
    then
        echo "bad luck"
    elif [[ $counter -eq 8 ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
