#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20
# 4 then "bad luck from China", 9  then "bad luck from Japan", 17 then "bad luck from Italy"

counter=0
while [ $((counter++)) -lt 20 ];do
    # echo $counter
    case $counter in
        "4")
            echo "bad luck from China"
            ;;
        "9")
            echo "bad luck from Japan"
            ;;
        "17")
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
done
