#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

hours=-1
while [ $((++hours)) -le 12 ];
do
    echo "Hour: $hours"
    minute=0
    while [ $((++minute)) -le 59 ];
    do
        echo $minute
    done
done
