#!/usr/bin/env bash
# Bash script that gives info about the school file.
# Using if,else statements

FILE="school"
if [ ! -e "$FILE" ];then
    echo "$FILE file does not exist"
    exit 0
fi
    echo "$FILE" file exists

    if [ -s "$FILE" ];
    then
        echo "$FILE file is not empty"
    else
        echo "$FILE file is empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "$FILE is a regular file"
    fi

