#!/usr/bin/env bash
# run server as nginx user
sudo chmod 666 /etc/nginx/nginx.conf
sed -i '1s/^/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
pkill apache2
su - nginx -c 'service nginx start'
